### ISSUE TITLE
[Ansible_Team] Facing issue with storops library on Python 3.10 version

### ISSUE THREAD

**Issue by dcsk1234** [emc-openstack/storops#352]
Ansible team has requirement of using **storops-1.2.10** library with **Python 3.1**0 version.

with above configuration, not able to execute unity ansible modules and below error is observed with respect to storops lib

from storops import UnitySystem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/storops/__init__.py", line 21, in <module>
    from storops.lib.thinclone_helper import TCHelper  # noqa
  File "/usr/local/lib/python3.10/site-packages/storops/lib/thinclone_helper.py", line 20, in <module>
    from persistqueue import PDict
ImportError: cannot import name 'PDict' from 'persistqueue' (/usr/local/lib/python3.10/site-packages/persistqueue/__init__.py)

**Ansible Env details:
ansible [core 2.12.1]**
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/automation/unity/feature-ANSUNITY-785-host-module-enhancements/ansible-unity-qe/host:/root/collections/unity:/root/collections/unity
  executable location = /usr/local/bin/ansible
  **python version = 3.10.0** (default, Jan 11 2022, 14:40:18) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
  jinja version = 3.0.3
  libyaml = True

Additional Info:
storops library is working fine with Python 3.9 and Ansible 2.12 in same environment
