### ISSUE TITLE
Compatibility issue between latest storops and requests2.9.1

### ISSUE THREAD

**Issue by yong-huang** [emc-openstack/storops#310]
In the Mitaka environment with latest storops (v1.2.4) installed, volume failed to create, error:

2020-05-08 07:35:42.126 10868 ERROR cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/storops/connection/client.py", line 127, in _cs_request
2020-05-08 07:35:42.126 10868 ERROR cinder.volume.manager     except requests.ConnectTimeout as ex:
2020-05-08 07:35:42.126 10868 ERROR cinder.volume.manager AttributeError: 'module' object has no attribute 'ConnectTimeout'

Reinstall storops with v0.5.7, the volume created successfully.

requests version is 2.9.1 which required by Mitaka:
/opt/stack/requirements/global-requirements.txt:requests>=2.8.1,!=2.9.0  # Apache-2.0
/opt/stack/requirements/upper-constraints.txt:requests===2.9.1

**Comment by Murray-LIANG** [comment]
I recalled that storops cannot work with requests 2.9.1. Requests 2.9.1 had some bugs with the http header.
